name: kcaa
version: 0.1.0
description: 'KCAA: Kancolle Automated Assistant'
dependencies:
  bootjack: any
  intl: any
  polymer: '>=0.15.1 <0.16.0'
transformers:
- polymer:
    entry_points: web/index.html
