name: kcaa
version: 0.1.0
description: 'KCAA: Kancolle Automated Assistant'
dependencies:
  bootjack: any
  intl: any
  json_object: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
