name: kcaa
version: 0.1.0
description: 'KCAA: Kancolle Automated Assistant'
dependencies:
  bootjack: any
  intl: any
  paper_elements: any
  polymer: '>=0.15.1 <0.16.0'
transformers:
- polymer:
    entry_points: web/index.html
    inline_stylesheets:
      packages/bootjack/css/bootstrap.min.css: false
      web/dialog/dialog.css: false
      web/kcaa.css: false
      web/predicate/predicate.css: false
